[package]
name = "smash_up"
version = "0.1.0"
authors = ["Dinah"]
edition = "2018"

[dependencies]
rand = "0.5.5"
glium = { version = "0.29", default-features = true }
image = "0.23"
imgui = "0.7.0"
imgui-glium-renderer = "0.7.0"
imgui-winit-support = "0.7.0"
